loader: "ns"
geotype: "structured_2D"
task: "dynamic_autoregressive"
scheduler: "OneCycleLR"
space_dim: 2
fun_dim: 10
out_dim: 1
attn_type: "selfAttention"
psi_dim: 16
n_hidden: 128
n_heads: 8
n_layers: 8
mlp_ratio: 1
slice_num: 32
unified_pos: 0
ref: 8
batch_size: 8
epochs: 500
teacher_forcing: 0
max_grad_norm: 0.1
