
model: 
  backbone: 
    "Garlekin"
  hc: 
    # None
    "mean_correction"  
path:
  root_dir: 
    "/vol/bitbucket/bd922/data/mindflow" # doc_machine
  save_dir: 
     'checkpoints/galerkin_transformer' # doc / local
    #  '/content/drive/MyDrive/hc_fluid/checkpoints/galerkin_transformer' # colab
hyper_parameters:
  num_epochs: 2
  batch_size: 1
  optimizer: "adamw"
  max_steps: 10
  learning_rate: 0.004
wandb_logging:
  wandb: False 
  project: "hc_fluid"
  run_name: "small_test_run"
  log_every: 10 # steps for logging loss
  image_log_every: 1 # epochs for image logging

optuna:
  num_trials: 20
  direction: "minimize"
  save_dir: "checkpoints/galerkin_transformer/optuna"
  run_name: "garlekin_fno2d_optuna"
  wandb_logging:
    wandb: False
  search_space:
    optimizer:
      type: "categorical"
      choices: ["adam", "adamw", "sgd"]
    learning_rate:
      type: "float"
      low: 1e-6
      high: 5e-3
      log: true
    batch_size:
      type: "categorical"
      choices: [4, 8, 16, 32]
